### ISSUE TITLE
Blocking Legacy Auth

### ISSUE THREAD

**Issue by DeanGross** [AlexFilipin/ConditionalAccess#31]
I don't see any policies for blocking legacy auth. Is there a reason that this is was not included?

**Comment by AlexFilipin** [comment]
It's included in all policy sets, however split up:
- 300 - <RING> - Attack surface reduction - All apps: Block access When using other clients
- 301 - <RING> - Attack surface reduction - All apps: Block access When using active sync

This allows you to block a first subset of legacy authN while you are working on the other

**Comment by DeanGross** [comment]
Awesome, thanks, I totally missed that.
