### ISSUE TITLE
Updates to include new options

### ISSUE THREAD

**Issue by DeanGross** [AlexFilipin/ConditionalAccess#36]
@AlexFilipin do you have any plans to update these to include new options, such as authentication strength?

**Comment by AlexFilipin** [comment]
@DeanGross While I did not have plans myself, @Timsto wanted to send some updates for the recent additions - I am currently pretty busy with other stuff but if Tim doesn't get a chance soon, I might just try to find a day to push some updates myself.

**Comment by AlexFilipin** [comment]
@DeanGross also, do you have specific policies in mind that you would like to see? Auth strength and policies based on app filter etc. are all pretty customer specific it will take some time to come up with something "generic".

**Comment by Timsto** [comment]
@DeanGross since the newest version. multiple new functions are included. If you need more, pls reach me out directly!
